AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens Carousel Static Website. This template deploys Kitten Carousel App on Served through Cloudfront and Route53.
Parameters:
  DomainName:
    Description: DNS Name of an existing Route53 Hosted Zone ex. clarusway.me
    Type: AWS::Route53::HostedZone::Id
  KittensDomainName:
    Description: Sub domain name for project exm. kittens.clarusway.us
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Must be a valid DNS Zone name
  
Resources:
  KittensBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: String
      BucketName: !Ref KittensDomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  KittensBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref KittensBucket #required
      PolicyDocument:
        Statement: 
          - Sid: PublicReadforKittensBucket
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Join ['',['arn:aws:s3:::', !Ref KittensBucket, '/*']]
  KittensCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: DISABLED
      DomainName: !Ref KittensDomainName  #required
      DomainValidationOptions:
        - DomainName: !Ref KittensDomainName
          HostedZoneId: !Ref DomainName
      ValidationMethod: DNS
  KittensDNSName:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: !Ref DomainName
      RecordSets:
        - Name: !Ref KittensDomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt KittensCloudfront.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
  KittensCloudfront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig: #required
        Aliases:
          - !Ref KittensDomainName
        DefaultCacheBehavior:
          TargetOriginId: KittensOriginId
          ViewerProtocolPolicy: allow-all
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt KittensBucket.WebsiteURL]]
            Id: KittensOriginId
            CustomOriginConfig:
                OriginProtocolPolicy: http-only
        ViewerCertificate:
          AcmCertificateArn: !Ref KittensCertificate
          SslSupportMethod: sni-only
        PriceClass: PriceClass_All
        DefaultRootObject: index.html
        HttpVersion: http2
        Enabled: True

Outputs:
  BucketName:
    Description: S3 Bucket URL for Kittens Website
    Value : !GetAtt KittensBucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront Distribution
    Value: !GetAtt KittensCloudfront.DomainName
  FullDomainName:
    Description: Full DomainName of Kittens Carousel Application
    Value: !Ref KittensDomainName